---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "ran2"
  namespace: "ztp-site"
spec:
  bindingRules:
    name: "ran2"
  mcp: "master"
  remediationAction: enforce
  sourceFiles:
    - fileName: PtpConfigSlaveCvl.yaml
      policyName: "config-policy"
      metadata:
        name: "du-ptp-slave"
      spec:
        profile:
          - name: "slave"
            # This interface must match the hardware in this group
            interface: "ens1f1"
            #ptp4lOpts: "-2 -s --summary_interval -4"
            #phc2sysOpts: "-a -r -n 24"
