---
# yamllint disable
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
 - goldwing-siteconfig.yaml

resources:
 - github.com/redhat-partner-solutions/vse-ocp-bases/base/ztp/site-config?ref=main

patches:
 - target:
    kind: Secret
   patch: |-
     - op: replace
       path: /metadata/name
       value: 'goldwing-bmc-creds-secret'
     - op: replace
       path: /metadata/namespace
       value: 'goldwing'
     - op: replace
       path: /data/username
       value: 'QURNSU4K'
     - op: replace
       path: /data/password
       value: 'YWx0aW9zdGFyITIz'
 - target:
    kind: SealedSecret
   patch: |-
     - op: replace
       path: /metadata/name
       value: 'assisted-deployment-pull-secret'
     - op: replace
       path: /metadata/namespace
       value: 'goldwing'
     - op: replace
       path: /spec/encryptedData/.dockerconfigjson
       value: 'J3siYXV0aHMiOnsiY2xvdWQub3BlbnNoaWZ0LmNvbSI6eyJhdXRoIjoiYjNCbGJuTm9hV1owTFhKbGJHVmhjMlV0WkdWMksyOWpiVjloWTJObGMzTmZaRFJrTW1NNE1XWTVOek16TkRrNU16azFNVFUxWldRMU9EUmtNelZrWWpFNlF6RkNWMHBDU1ZRMlIwa3pSRTVZTXpZMlZGTlVSa3N6VTFoWlRsRllNRll5VFVKTE9ETXhTRE5UV2pOV01FMVRXVXcxVWpaUFFqSkdTVFZVUWpaUVRnPT0iLCJlbWFpbCI6ImhoYW1pZEByZWRoYXQuY29tIn0sInF1YXkuaW8iOnsiYXV0aCI6ImIzQmxibk5vYVdaMExYSmxiR1ZoYzJVdFpHVjJLMjlqYlY5aFkyTmxjM05mWkRSa01tTTRNV1k1TnpNek5EazVNemsxTVRVMVpXUTFPRFJrTXpWa1lqRTZRekZDVjBwQ1NWUTJSMGt6UkU1WU16WTJWRk5VUmtzelUxaFpUbEZZTUZZeVRVSkxPRE14U0ROVFdqTldNRTFUV1V3MVVqWlBRakpHU1RWVVFqWlFUZz09IiwiZW1haWwiOiJoaGFtaWRAcmVkaGF0LmNvbSJ9LCJxdWF5LmlvL3JlZGhhdC1wYXJ0bmVyLXNvbHV0aW9ucyI6eyJhdXRoIjoiY21Wa2FHRjBMWEJoY25SdVpYSXRjMjlzZFhScGIyNXpLM0psWkdoaGRIUmxjM1JvWVhKdVpYTnpPamxCTWpCWlVGVkJTVEJQV0VkWVVFNU5NbGxFTTFKTlIwc3lWVlF3U0ZjelIxTXdXVU15T0ZveFZGVklRazQwVGxBMlFsWkdUMDVWVjBaYU4xcEtSRTg9In0sInF1YXkuaW8vcHJlZ2EiOnsiYXV0aCI6ImNISmxaMkVyY0hKbFoyRTZURkUzTTA5UVdGbEpURVU1VGxWTU9WRlhTbGhQT1VsWlZEWklRek5PUWs1VFVsTkpWMVpXUWtsQ05GTXpRbGRGVmtSWlZFazRXRXMxVERSVlRqTkxNUT09In0sICJhbHRpb3N0YXItcmVnaXN0cnkuY2Fycy5sYWI6NTAwMCI6eyJhdXRoIjogIlUzUnlkVzVuVDNWME9sQnliM1J2ZEhsd1pYTkJibVJRWVdsdWEybHNiR1Z5YzFSeVlXTnJNZz09In0sInJlZ2lzdHJ5LmNvbm5lY3QucmVkaGF0LmNvbSI6eyJhdXRoIjoiZkhWb1l5MXdiMjlzTFRRNE0yRTFObU5sTFRVelpqVXROR0UzWmkwNE9XUTVMVGRtTlRRd01qRXdNV1U0TURwbGVVcG9Za2RqYVU5cFNsTlZlbFY0VFdsS09TNWxlVXA2WkZkSmFVOXBTVEpOZWtGNlRrUk5OVTFFVVROTmVtc3dUVmRXYTA5SFNtaGFSR2N4VGxkT2FGcHFUbTFaVkdSb1RrTktPUzVETTNKdVVuUXpkalV6Y0VWZlFVbFRUMkpsYXkxUlgwUlphVjlIZUhRNWJIcHBlRTFrWVdsQmQyODNTV054VHpCelJsSmllbXRSVmpGUE0yTjBiMGhCTm5KUU0wRmpjWE5hTFdscFdtbzNlREZKYnkxak9WaGhiV3cxZEhSemFGOTNWbkpSZHpJeWRIaDZhalp0U3kxMFFWVnBOVVpXTjBOQ00zRkljVmczVlVwaE1GRXhha1J3ZUdGdU9VWlhjVGRXY0U5UFlYbHROV2hYWTNSR1FuQmZOVTAxUTNFd1N6VlJPVzVuY2tOUlVHOUdRakUzTWxWSlYzaDVha3hLWHpST09IaExkbTQwTTNaWmRHbzBXbmhzT0RjM1UxVkpTSGRITUVRM1gwUldPVXh4T0ZsblFXczRVamxFT1ZGWE0yaGhiVUp3VmpsU1VqUTJTazU2ZVRRelZEbFRWWGwwZDBaTWEyUTNZMVp0TFdsdlprMVBiMk52U2xwVlRsTnBkMFppVTJOclJEbFZWbGN5YW1wbVlXVTFabVZSUTJSb2FUUmhiRjh5Vm1RMmNXaE9la2xNVjBvd1kzaG5kak15VTNCcmNIaEhaVE55V1RoR1QzTmlSMll6ZUhsT00xTnljMFJ5ZW1OMVRYWm9jVkoxUm14YVExVmhPRVpxWlhOS1V6WjBTMFpNV21semJtVklTRXB4YlU5YVNsRnZRV1pXYTBrNWRrZG5SazEzU2pOdlFXNUNaa2d6YlZvdGMyZEJla0ZTVFhZM1dGQm5jazVOVVZsUE5HOUVOSGhFVEc5WWQwNWlSV2x6Ymxaa1MyMXJPRmd3VTE4MFgyczNVbUUyTW5KcFUwTklSazVHWmtaUlJFVkxUblpmVkdsRU1sbEhSWGM1TldOdlVWaElja3hWVEd0Q2RuSjBZekJVYWxSUlgxaGpkSE5TY0hBMWRXVTRkMTlST1c5dGRFTnlVMjFKVkVGS2QwNUhNbTlUUlVOMk1WZHRWemR6TFhodWNWRndjVkowYUZodU5FZERWVmR4YW5OWWJXdFFjVTVHVm5SbWRHeExWRUp4YTFSaU5EbFNXbmhXYWtWM1pTMDNPR3RuWnpCVVkwSlRRa3R3TldGblQycHdSelZXUWxBMWJXdGFXVTlwUmtONk9XcERNamM0UzA1cFVqQjFVblk1UVdFMVJHTnRWVFpsVFVsblVUSmFjdz09IiwiZW1haWwiOiJoaGFtaWRAcmVkaGF0LmNvbSJ9LCJyZWdpc3RyeS5yZWRoYXQuaW8iOnsiYXV0aCI6ImZIVm9ZeTF3YjI5c0xUUTRNMkUxTm1ObExUVXpaalV0TkdFM1ppMDRPV1E1TFRkbU5UUXdNakV3TVdVNE1EcGxlVXBvWWtkamFVOXBTbE5WZWxWNFRXbEtPUzVsZVVwNlpGZEphVTlwU1RKTmVrRjZUa1JOTlUxRVVUTk5lbXN3VFZkV2EwOUhTbWhhUkdjeFRsZE9hRnBxVG0xWlZHUm9Ua05LT1M1RE0zSnVVblF6ZGpVemNFVmZRVWxUVDJKbGF5MVJYMFJaYVY5SGVIUTViSHBwZUUxa1lXbEJkMjgzU1dOeFR6QnpSbEppZW10UlZqRlBNMk4wYjBoQk5uSlFNMEZqY1hOYUxXbHBXbW8zZURGSmJ5MWpPVmhoYld3MWRIUnphRjkzVm5KUmR6SXlkSGg2YWpadFN5MTBRVlZwTlVaV04wTkNNM0ZJY1ZnM1ZVcGhNRkV4YWtSd2VHRnVPVVpYY1RkV2NFOVBZWGx0TldoWFkzUkdRbkJmTlUwMVEzRXdTelZST1c1bmNrTlJVRzlHUWpFM01sVkpWM2g1YWt4S1h6Uk9PSGhMZG00ME0zWlpkR28wV25oc09EYzNVMVZKU0hkSE1FUTNYMFJXT1V4eE9GbG5RV3M0VWpsRU9WRlhNMmhoYlVKd1ZqbFNValEyU2s1NmVUUXpWRGxUVlhsMGQwWk1hMlEzWTFadExXbHZaazFQYjJOdlNscFZUbE5wZDBaaVUyTnJSRGxWVmxjeWFtcG1ZV1UxWm1WUlEyUm9hVFJoYkY4eVZtUTJjV2hPZWtsTVYwb3dZM2huZGpNeVUzQnJjSGhIWlROeVdUaEdUM05pUjJZemVIbE9NMU55YzBSeWVtTjFUWFpvY1ZKMVJteGFRMVZoT0VacVpYTktVelowUzBaTVdtbHpibVZJU0VweGJVOWFTbEZ2UVdaV2EwazVka2RuUmsxM1NqTnZRVzVDWmtnemJWb3RjMmRCZWtGU1RYWTNXRkJuY2s1TlVWbFBORzlFTkhoRVRHOVlkMDVpUldsemJsWmtTMjFyT0Znd1UxODBYMnMzVW1FMk1uSnBVME5JUms1R1prWlJSRVZMVG5aZlZHbEVNbGxIUlhjNU5XTnZVVmhJY2t4VlRHdENkbkowWXpCVWFsUlJYMWhqZEhOU2NIQTFkV1U0ZDE5Uk9XOXRkRU55VTIxSlZFRktkMDVITW05VFJVTjJNVmR0VnpkekxYaHVjVkZ3Y1ZKMGFGaHVORWREVlZkeGFuTlliV3RRY1U1R1ZuUm1kR3hMVkVKeGExUmlORGxTV25oV2FrVjNaUzAzT0d0blp6QlVZMEpUUWt0d05XRm5UMnB3UnpWV1FsQTFiV3RhV1U5cFJrTjZPV3BETWpjNFMwNXBVakIxVW5ZNVFXRTFSR050VlRabFRVbG5VVEphY3c9PSIsImVtYWlsIjoiaGhhbWlkQHJlZGhhdC5jb20ifSwiYnJldy5yZWdpc3RyeS5yZWRoYXQuaW8iOnsiYXV0aCI6ImFHaGhiV2xrUUhKbFpHaGhkQzVqYjIwNk56ZzJMVWhoYlhwaGFHRnRhV1E9In19fSc='
     - op: replace
       path: /spec/encryptedData/type
     - op: replace
       path: /spec/template/metadata/name
       value: 'goldwing-bmc-creds-secret'
     - op: replace
       path: /spec/template/metadata/namespace
       value: 'goldwing'
