---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  # yamllint disable-line rule:line-length
  # The name will be used to generate the placementBinding and placementRule names as {name}-placementBinding and {name}-placementRule
  name: "group-hpe"
  namespace: "ztp-group"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    group-hpe: ""
  mcp: "master"
  sourceFiles:
    - fileName: ConsoleOperatorDisable.yaml
      policyName: "config-policy"
    - fileName: StorageClass.yaml
      policyName: "config-policy"
      metadata:
        name: "lso-filesystemclass"
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
    - fileName: DisableSnoNetworkDiag.yaml
      policyName: "config-policy"
    - fileName: PerformanceProfile.yaml
      policyName: "config-policy"
      spec:
        cpu:
          isolated: "4-47,52-63"
          reserved: "0-3,48-51
          hugepages:
             defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 32
          workloadHints:
          realTime: true
          highPowerConsumption: false
          perPodPowerManagement: false
    - fileName: TunedPerformancePatch.yaml
      policyName: "config-policy"
      spec:
        profile:
          - name: performance-patch
            data: |
              [main]
              summary=Configuration changes profile inherited from performance created tuned
              include=openshift-node-performance-openshift-node-performance-profile
              [sysctl]
              kernel.timer_migration=1
              [scheduler]
              group.ice-ptp=0:f:10:*:ice-ptp.*
              group.ice-gnss=0:f:10:*:ice-gnss.*
              [service]
              service.stalld=start,enable
              service.chronyd=stop,disable
