name: Yaml Lint Check
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: Validate Manifests
        run: yamllint . -f github
